<h3 style = "color : green"><center><bold>CODE</bold></center></h3>

In [1]:
import numpy as np

mat_1 = np.array(np.random.randint(10,size=(3,4)))
mat_2 = np.array(np.random.randint(10,size=(3,4)))

print("First Matrix : \n" , mat_1)
print("\nSecond Matrix : \n",mat_2)

#Multiplicaton

mul_mat = mat_1 * mat_2
print("\nMatrix Multiplication : \n",mul_mat)
print("\nDisplaying Specific Rows of Matrix : \n" ,mul_mat[:2,:])
print("\nDisplaying Specific Columns of Matrix : \n" ,mul_mat[:,2:4])

#Addition
add_mat = mat_1 + mat_2
print("\nMatrix Addition : \n",add_mat)
print("\nDisplaying Specific Rows of Matrix : \n" ,add_mat[:2,:])
print("\nDisplaying Specific Columns of Matrix : \n" ,mul_mat[:,1:2])

#Subtraction
sub_mat = mat_1 - mat_2
print("\nMatrix Subtraction : \n",sub_mat)
print("\nDisplaying Specific Rows of Matrix : \n" ,sub_mat[:2,:])
print("\nDisplaying Specific Columns of Matrix : \n" ,mul_mat[:,:1])


First Matrix : 
 [[8 4 4 9]
 [2 6 1 8]
 [0 6 7 8]]

Second Matrix : 
 [[5 4 5 0]
 [4 6 9 0]
 [4 2 9 2]]

Matrix Multiplication : 
 [[40 16 20  0]
 [ 8 36  9  0]
 [ 0 12 63 16]]

Displaying Specific Rows of Matrix : 
 [[40 16 20  0]
 [ 8 36  9  0]]

Displaying Specific Columns of Matrix : 
 [[20  0]
 [ 9  0]
 [63 16]]

Matrix Addition : 
 [[13  8  9  9]
 [ 6 12 10  8]
 [ 4  8 16 10]]

Displaying Specific Rows of Matrix : 
 [[13  8  9  9]
 [ 6 12 10  8]]

Displaying Specific Columns of Matrix : 
 [[16]
 [36]
 [12]]

Matrix Subtraction : 
 [[ 3  0 -1  9]
 [-2  0 -8  8]
 [-4  4 -2  6]]

Displaying Specific Rows of Matrix : 
 [[ 3  0 -1  9]
 [-2  0 -8  8]]

Displaying Specific Columns of Matrix : 
 [[40]
 [ 8]
 [ 0]]
