<h3 style = "color : green"><center><bold>CODE</bold></center></h3>

In [33]:
import numpy as np

#Creating matrix having some negative values
matrix = np.array(np.random.randn(3,4))
print("Original Matrix : \n" ,matrix)

#Taking absolute values
abs_matrix = abs(matrix)
print("\nMatrix After taking Absolute value : \n",abs_matrix)

#Extraxting negative values
neg_mat = []
for i in range(3):
    for j in range(4):
        if(matrix[i,j] < 0):
            neg_mat.append(matrix[i,j])
        else :
            pass
print("\nNegative Values in Original Matrix : \n",neg_mat)


#Adding a row to Original matrix
Arow_matrix = np.insert(matrix,3,[2,3,4,4],axis=0)
print("\nMatrix after adding Row at last : \n" ,Arow_matrix)

#Adding a column to Original matrix
Acol_matrix = np.insert(matrix,3,[22,13,14],axis=1)
print("\nMatrix after adding Column : \n" ,Acol_matrix)

#Removing a row from Original matrix
drow_matrix = np.delete(matrix,2,axis=0)
print("\nMatrix after Removing Row : \n" ,drow_matrix)

#Removing a column from Original matrix
dcol_matrix = np.delete(matrix,2,axis=1)
print("\nMatrix after Removing Column : \n" ,dcol_matrix)


#Finding Maximum
maxx = np.max(matrix)
print("\nMaximum Value in Matrix : ",max)

#Finding Minimum 
minn = np.min(matrix)
print("\nMinimum Value in Matrix : ",min)

#Finding Maximum in row
row_max = np.max(matrix,axis=0)
print("\nMaximum Value in Matrix in Each row : \n",row_max)

#Finding Minimum in row
row_min = np.min(matrix,axis=0)
print("\nMinimum Value in Matrix in each row : \n",row_min)

#Finding Maximum in Column
col_max = np.max(matrix,axis=1)
print("\nMaximum Value in Matrix in Column: \n",col_max)

#Finding Minimum in Column
col_min = np.min(matrix,axis=1)
print("\nMinimum Value in Matrix Column : \n",col_min)

#Sum of Elements in Matrix
sum_mat = sum(matrix)
print("\nSum of All Elements : \n",sum_mat)


Original Matrix : 
 [[-2.05572711  1.76090283  0.661182    0.67913188]
 [ 0.25218582  1.46135841  0.24888084  0.42448135]
 [ 0.434033   -0.50470116  0.74765005  0.58078181]]

Matrix After taking Absolute value : 
 [[2.05572711 1.76090283 0.661182   0.67913188]
 [0.25218582 1.46135841 0.24888084 0.42448135]
 [0.434033   0.50470116 0.74765005 0.58078181]]

Negative Values in Original Matrix : 
 [-2.055727112369363, -0.5047011636621914]

Matrix after adding Row at last : 
 [[-2.05572711  1.76090283  0.661182    0.67913188]
 [ 0.25218582  1.46135841  0.24888084  0.42448135]
 [ 0.434033   -0.50470116  0.74765005  0.58078181]
 [ 2.          3.          4.          4.        ]]

Matrix after adding Column : 
 [[-2.05572711  1.76090283  0.661182   22.          0.67913188]
 [ 0.25218582  1.46135841  0.24888084 13.          0.42448135]
 [ 0.434033   -0.50470116  0.74765005 14.          0.58078181]]

Matrix after Removing Row : 
 [[-2.05572711  1.76090283  0.661182    0.67913188]
 [ 0.25218582  1