Create/Define single dimension / multi-dimension arrays, and arrays with specific values like
array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

In [1]:
import numpy as np

In [16]:
#One-D arrays

zero_1D = np.zeros(5)
ones_1D = np.ones(5)
random_1D = np.array(np.random.randn(4))

print("Zero 1-D Array : ",zero_1D)
print("Ones 1-D Array : ",ones_1D)
print("Random 1-D Array : ",random_1D)

#2-D array
zero_2D = np.zeros((4,5))
ones_2D = np.ones((6,5))
random_2D = np.array(np.random.randn(4,4))
dia_mat = np.diag([2,5,6,8])

print("\nZero 2-D Array : \n",zero_2D)
print("\nOnes 2-D Array : \n",ones_2D)
print("\nRandom 2-D Array : \n",random_2D)
print("\nDiagonal Matrix : \n" ,dia_mat)

Zero 1-D Array :  [0. 0. 0. 0. 0.]
Ones 1-D Array :  [1. 1. 1. 1. 1.]
Random 1-D Array :  [ 0.46583408 -0.47685351 -0.04729039 -0.71363148]

Zero 2-D Array : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones 2-D Array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Random 2-D Array : 
 [[-2.68362075e-02 -1.21119935e-01  7.25275670e-01 -3.84243165e-01]
 [ 2.00684896e+00  6.08714970e-01 -7.15201376e-04 -9.24857254e-01]
 [-2.30573490e-01 -6.62856103e-01 -1.47482224e-02  1.08577568e+00]
 [ 1.18936165e+00 -4.06803719e-01  2.78240267e-01  8.13573865e-01]]

Diagonal Matrix : 
 [[2 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
